### ISSUE TITLE
Working demo with babel6 + karma

### ISSUE THREAD

**Issue by fernandofleury** [douglasduteil/isparta#104]
I've bumping my head to make proper babel6 code coverage using isparta + karma.

Right now this is the error I get from it:

`Post-processing using source maps Nothing mapped from file:`

My karma config:

``` javascript
coverageReporter: {
      instrumenters: {
        isparta : require('isparta')
      },
      instrumenter: {
        '*.js': 'isparta'
      }
    },
babelPreprocessor: {
      options: {
        sourceMap: 'inline'
      }
    },
```

**Comment by trodrigues** [comment]
Same here, without karma. I just get `No coverage information was collected, exit without writing coverage information` with no other information or error output.

**Comment by fernandofleury** [comment]
As in right now, I can generate a pseudo babel6 coverage:

![image](https://cloud.githubusercontent.com/assets/2780941/12153699/7a3c5556-b4a2-11e5-8c9f-324d62538511.png)

As you can see, the generated coverage is not properly formatted. I will try to fork the project and update istanbul peerdep.

**Comment by kt3k** [comment]
This is my example of generating es6 coverage report with karma + karma-browserify + isparta(v4).
https://github.com/kt3k/karma-browserify-isparta-example
https://codecov.io/github/kt3k/karma-browserify-isparta-example?branch=master

**Comment by fernandofleury** [comment]
@kt3k That's a pretty clever ideia. I've managed to make it work as well!

**Comment by kt3k** [comment]
Currently istanbul's official [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) can instrument es6 code. I think that is now the most reliable way to create coverage report of es6 scripts.
