### ISSUE TITLE
Isparta stops working with istanbul > 0.4.4

### ISSUE THREAD

**Issue by queicherius** [douglasduteil/isparta#123]
Isparta works perfectly fine with istanbul `0.4.4`, but as soon as `0.4.5` is installed, it exits out with 

> No coverage information was collected, exit without writing coverage information

I realise this repository is not maintained anymore, but it would still be neat to lock the version to something that worked. :)

**Comment by Mrparkers** [comment]
@queicherius You should switch over to [nyc](https://github.com/istanbuljs/nyc) and[ babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul)

**Comment by queicherius** [comment]
I know that, and I use it in my newer projects, but the ones that I didn't update yet just broke when I ran `npm update` and it loaded a **patch version** of a dependencies dependency. That shouldn't happen.

**Comment by Mrparkers** [comment]
Yeah, but it's not this package's fault, it's the fault of `istanbul` for not respecting semantic versioning.

**Comment by H34D** [comment]
see here https://github.com/douglasduteil/isparta/issues/126

**Comment by queicherius** [comment]
@H34D Your workaround is in the PR I put up (#124) 2 weeks ago, but not sure if that'll ever get merged. Some tests are failing, but it's not because of the dependency as far as I can tell.

**Comment by queicherius** [comment]
Seems like this will not ever make it in
