### ISSUE TITLE
Isparta stopped collecting code coverage info

### ISSUE THREAD

**Issue by MoonTahoe** [douglasduteil/isparta#126]
Isparta was working well for me in several projects, but all of the sudden it stopped generating code coverage in all of them.

Here is my test command

```
./node_modules/.bin/babel-node ./node_modules/.bin/isparta cover ./node_modules/.bin/_mocha -- --require ./test/setup.js --require ./node_modules/ignore-styles --recursive
```

The tests pass, but where there used to be code coverage info...

```
No coverage information was collected, exit without writing coverage information
```

Again, **isparta** was generating code coverage. When I found that it was no longer working, I checked across a few projects on two separate macs and received the same results.

Is there a way to find out why code coverage reports are not being generated?

Also, if I change to **babel-istanbul**

```
./node_modules/.bin/babel-node ./node_modules/.bin/babel-istanbul cover ./node_modules/.bin/_mocha -- --require ./test/setup.js --require ./node_modules/ignore-styles --recursive
```

The tests pass and I get code coverage. The problem with babel-istanbul is that it does not give me accurate coverage with ES6 `export default` statements. I moved to isparta and solved this problem a few weeks ago, but now I am back at square one.

**Comment by H34D** [comment]
just add "istanbul": "0.4.4", to your package.json, clean node modules and npm install. took me 2 days to find out. @douglasduteil i would strongly recommend setting the reference in the package.json of isparta to "istanbul": "0.4.4", instead of "istanbul": "^0.4.0". This will restore compatibility if this package is not longer maintained.

**Comment by MoonTahoe** [comment]
Great! Works for me! Thanks for responding to this so quickly. I really appreciate it.

**Comment by claudio-viola** [comment]
Thank you for sharing the issue! Crazy stuff!

**Comment by Jinjiang** [comment]
I am also trapped in this issue. Is there any new version update for `istanbul@0.4.4` soon?

**Comment by lijunle** [comment]
I want to mention that, @H34D 's [method](https://github.com/douglasduteil/isparta/issues/126#issuecomment-245666428) does not work for yarn. 😭

**Comment by erwin16** [comment]
lijunle commented on Nov 15, 2016 : @H34D 's method does not work for yarn.

Any obvious reason why it does not work w yarn ?  I also had to use npm to make it running...

**Comment by codingthat** [comment]
I'm having this issue trying to set up with isparta for the first time, based on a template.  I tried both yarn and npm install, but either way I get passing tests and then "No coverage information was collected, exit without writing coverage information."

My dev dependencies has `    "isparta": "^4.0.0",` and the npm script is `babel-node node_modules/.bin/isparta cover _mocha`.

.babelrc simply has:

```
{
  "presets": ["es2015"]
}
```

Any ideas?
