### ISSUE TITLE
Babel/6to5 options don't work

### ISSUE THREAD

**Issue by simonzack** [douglasduteil/isparta#19]
I'm getting syntax errors when using `{blacklist: ['regenerator']}`.

**Comment by douglasduteil** [comment]
? Where did you put this ? Can you give me more details ?

**Comment by simonzack** [comment]
Here's my karma config:

    var istanbul = require('browserify-istanbul');

    {
      frameworks: ['browserify', 'mocha'],
      reporters: ['progress'],
      files: ['*.js'],
      preprocessors: {
        '*.js': ['browserify'],
      },
      browserify: {
        istanbul({instrumenter: isparta, instrumenterOptions: {isparta: {blacklist: ['regenerator']}})
      },
    },

Taking a wild guess, perhaps istanbul sees the generator as a syntax error?

**Comment by douglasduteil** [comment]
K The syntax error is legit you missed a key in the `browserify` object :

```diff
var istanbul = require('browserify-istanbul');

{
  frameworks: ['browserify', 'mocha'],
  reporters: ['progress'],
  files: ['*.js'],
  preprocessors: {
    '*.js': ['browserify'],
  },
  browserify: {
-    istanbul({instrumenter: isparta, instrumenterOptions: {isparta: {babel: {blacklist: ['regenerator']}}})
+    transform: istanbul({instrumenter: isparta, instrumenterOptions: {isparta: {babel: {blacklist: ['regenerator']}}})
  },
},
```

The options problem might be related to #5. I didn't test the `browserify-istanbul` compatibility by @lukescott config seems to work.

I guess for you it would be like : 

```js
var isparta = require("isparta");
var istanbul = require("browserify-istanbul");

// [...]

browserify: {
  transform: [istanbul({
    instrumenter: new isparta.Instrumenter({
      to5Options: {
        blacklist: ['regenerator']
      }
    })
  })]
}
```

**Comment by simonzack** [comment]
@douglasduteil I don't think that's related as that's a problem I ended up fixing in browserify-istanbul :) You could close that issue, btw. And sorry about the poor example, I did make a syntax error in my comment but it's not present in my code. The syntax error refers to my use of generators.

**Comment by douglasduteil** [comment]
Alright :)

**Comment by simonzack** [comment]
@douglasduteil No I meant #5, not this one :p, I'm still having issues with this one.

**Comment by douglasduteil** [comment]
Oops

**Comment by lukescott** [comment]
Remember to change to5Options to babelOptions since 61853e3a2cd815b3a74b34bd150e54545283c1de.

**Comment by douglasduteil** [comment]
I'm closing this for now. Feel free to reopen it if you still have this issue.
