### ISSUE TITLE
[Study result]: wrong coverage skipping format for functions

### ISSUE THREAD

**Issue by douglasduteil** [douglasduteil/isparta#20]
# The additional babel functions aren't ignored ! 

![code coverage report for study node path es6 index js](https://cloud.githubusercontent.com/assets/730511/6228840/08f979a4-b6b1-11e4-887f-6dded2276180.png)

Parts of the generated coverage result are wrong. I'm assigning `skip` at the location level for all the metrics but for the functions it's suppose to be assigned at the root of the metric.

### Expected metric models

- For a statements
```js
{
  "0": {
      "start": {
          "line": 7,
          "column": 0
      },
      "end": {
          "line": 7,
          "column": 13
      },
      "skip": true
  }
}
```

- For a functions 
```js
{
  "0": {
    "name": "foo",
    "line": 16,
    "loc": {
      "start": {
        "line": 16,
        "column": 0
      },
      "end": {
        "line": 16,
        "column": 15
      }
    },
    "skip": true
  }
}
```

- For a branches 
```js
{
  "0": {
    "line": 12,
    "type": "cond-expr",
    "locations": [{
      "start": {
        "line": 12,
        "column": 19
      },
      "end": {
        "line": 12,
        "column": 20
      },
      "skip": true
    }, {
      "start": {
        "line": 12,
        "column": 23
      },
      "end": {
        "line": 12,
        "column": 24
      },
      "skip": true
    }]
  }
}
```

**Comment by Alxandr** [comment]
I noticed the same. I have 0 test coverage (I don't even load the file), yet istanbul reports more than 80%. I guess this is due to huge amounts of regenerator code being marked as "ignore". Would love it if you can figure out a solution to this problem :).

**Comment by douglasduteil** [comment]
Working on it :)

**Comment by Alxandr** [comment]
What happens if you instead of just changing locs to ignored, delete the fns and branches and statements that it does not find in the sourcemap?

**Comment by douglasduteil** [comment]
> What happens if you instead of just changing locs to ignored, delete the fns and branches and statements that it does not find in the sourcemap?

Some other bugs pop up. It might be a smart solution but it was faster for me to just skip them for now.
Might be investigate this with the new code base. Thanks @Alxandr

**Comment by Alxandr** [comment]
Well, as long as you get the correct metrics (or almost correct), it shouldn't much matter :). I was just throwing out ideas in case you were stuck. I tried working on it myself, but had problems with node-debugger, which made debugging a pita.

**Comment by Alxandr** [comment]
I'm still getting a huge amount of success rate, even when the file isn't run at all:

![image](https://cloud.githubusercontent.com/assets/112334/6338574/24666ad6-bbb0-11e4-8168-a2738798fe65.png)

**Comment by Alxandr** [comment]
In case there's interest for it, I have a seemingly working one here: https://github.com/YoloDev/kake-istanbul/blob/master/src/instrumenter.js

**Comment by douglasduteil** [comment]
... Alright I start refactoring to remove the additional metrics
Wait for it :+1:

**Comment by douglasduteil** [comment]
... Far more difficult that expected...
the `getPreamble` function I overwrite in Isparta isn't the last coverage hook. Some data are added after it so even if I manage to remove generated statement there it's outputting `NaN` results here and there...

**Comment by Alxandr** [comment]
I already fixed all of that though. https://coveralls.io/builds/1983300/source?filename=src%2Findex.js

It's handled by the static function in the previous link I sent you.

**Comment by cvbuelow** [comment]
I don't know if this is related but I'm getting some strange results...this code should have 100% coverage but doesn't

![screen shot 2015-05-29 at 3 38 57 pm](https://cloud.githubusercontent.com/assets/1081493/7918733/8a48c7ec-0861-11e5-9546-6a510b53e072.png)

**Comment by douglasduteil** [comment]
I'm closing this for now. Feel free to reopen it if you still have this issue.
