### ISSUE TITLE
cli: how to use `.es6` extension both for src and tests?

### ISSUE THREAD

**Issue by deepsweet** [douglasduteil/isparta#29]
```sh
$ babel-node node_modules/.bin/isparta cover node_modules/.bin/_mocha -- test/*.es6

...

4 passing (7ms)

No coverage information was collected, exit without writing coverage information
```

original `istanbul cover` has `-i` option for this:

```sh
      -i <include-pattern> [-i <include-pattern>]
              one or more fileset patterns e.g. "**/*.js"
```

**Comment by deepsweet** [comment]
any ideas?..
even changing it here https://github.com/douglasduteil/isparta/blob/master/src/cli.js#L138 doesn't help.

**Comment by roman01la** [comment]
Actually includes for *.es6 source files does work, but there's no command line argument to pass in the pattern as you've mentioned.

But to use test files with custom extension relates directly to test framework you are using.
It's possible in case of mocha:

```
isparta cover _mocha --report lcovonly -- test/**/*.es6 -r babel/register
```

**Comment by roman01la** [comment]
I'm working on PR for `include` option. But it seems it seems like `nomnom` module doesn't handle glob patterns right and it also haven't been updated in awhile, since November.

I'm going to replace arguments parser.

**Comment by deepsweet** [comment]
looks like @douglasduteil doesn't have time for PRs :(

**Comment by roman01la** [comment]
At least this can be considered to merge when Isparta is going to be merged into Istanbul.

**Comment by roman01la** [comment]
Ok, this should work. The changes didn't require replacement for `nomnom`, basically it's simplified workaround taken from Mocha.

**Comment by jedmao** [comment]
@roman01la this fix isn't working for me. My error is the same as @deepsweet and I'm using isparta@3.0.3:

```
No coverage information was collected, exit without writing coverage information
```

What is the exact CLI command that should be used to include *.es6 files? Does the glob need to be surrounded by quotes?

Is this just passing through the `-i, --include` flag directly to Instanbul or is there something else happening before it goes to Istanbul?

@deepsweet did you ever get this working?

The command I've been trying is thus:

```
babel-node node_modules/isparta/bin/isparta cover --include test/*.es6 node_modules/mocha/bin/_mocha
```

I've tried with and without quotes, putting the `--include` option after the mocha command and also tried putting `-- --include test/*.es6` after the mocha command.

Any ideas?

**Comment by deepsweet** [comment]
it's working fine for me https://github.com/yummies/yummies/blob/master/package.json#L45

**Comment by jedmao** [comment]
@deepsweet thanks! Unfortunately, that's throwing the same error :(

It wasn't runnign on Windows, however, so I had to modify the command a bit:

```json
{
  "scripts": {
    "cover": "isparta cover node_modules/mocha/bin/_mocha -i test/*.es6 --report lcovonly"
  }
}
```

Note, I also have a `mocha.opts` file in the `test/` folder:

```
--inline-diffs
--reporter spec
--require babel-core/register
test/*.es6
```

Not sure if that has anything to do with it, but I've tried all sorts of variations and I get the same damn error!

**Comment by jedmao** [comment]
@deepsweet problem solved. I had mistakenly referenced `test/*.es6` instead of `lib/*.es6`. Thanks again!

**Comment by roman01la** [comment]
Not sure, but looks like it works only with one level deep files lib/*.es6, but not with lib/**/*.es6

**Comment by jedmao** [comment]
Yes. That part was intentional. Thanks.
