### ISSUE TITLE
Karma server crashing with isparta/istambul

### ISSUE THREAD

**Issue by rysilva** [douglasduteil/isparta#34]
I have a grunt karma configuration with browserify options like this:

    browserify: {
        debug: true,
        transform: [['browserify-istanbul', {instrumenter: require('isparta')}]]
    }

When I run `grunt karma:unit:start watch`, the server never starts and I get an anonymous ">> Error" with no explanation, even with --verbose.  The server is not running, and so the tests can't run.

`grunt karma:once` (with `singleRun: true`) works great.

I wouldn't expect this to have anything to do with isparta except that when I change my browserify options to simply

    transform: ['babelify']

Then it works fine (though of course coverage isn't right)

My config roughly looks like this:

```
{
        options: {
            basePath: '',
            frameworks: ['browserify', 'jasmine'],

            preprocessors: {
                '<%= config.source %>/**/!(*spec|templates).js': [ 'browserify']
            },

            browserify: {
                debug: true,
                transform: [['browserify-istanbul', {instrumenter: require('isparta')}]]
                //This one works:
                //transform: [['babelify', { 'sourceMapRelative': '<%= config.source %>' }]]
            },

            reporters: ['dots', 'coverage'],
            coverageReporter: {
                reporters: [
                    { type: 'html' }
                ]
            },
            port: 9888,
            logLevel: 'INFO',
            browsers: ['PhantomJS']
        },
        unit: {
            background: true,
            singleRun: false,
            files: {
                src: ["<%= config.source %>/**/*.js"]
            }
        },
        once: {
            singleRun: true,
            files: '<%= karma.unit.files %>'
        }
    }
```

**Comment by douglasduteil** [comment]
I'm closing this for now. Feel free to reopen it if you still have this issue.

**Comment by rysilva** [comment]
It is still an issue but so much time has passed that it will take some work to look at this again.  I have been running only in singlerun mode though, so I would love to get it resolved.  Don't know if it's a grunt issue or not, so I guess running native karma would be the first step.
