### ISSUE TITLE
npm package is completely broken 

### ISSUE THREAD

**Issue by PinkaminaDianePie** [douglasduteil/isparta#35]
/lib folder is in .gitignore
/src folder is in .npmignore
so if i install this module by "npm install --save-dev douglasduteil/isparta" comand ill have almost empty folder in node_modules, without sources and without build (thx to @deepsweet, he broke package with https://github.com/douglasduteil/isparta/commit/bd871108e8d782abfdf184a3402d26d1ed00c92a commit ). current node_modules/isparta structure is:
```
bin
node_modules
LICENSE
package.json
README.md
.npmignore
```

**Comment by deepsweet** [comment]
I completely broke isparta because I don't want to download completely useless files every time I install package the normal way (from npm, not from github repo).

I'm not sure that you understand the difference between `npm install isparta` and `npm install douglasduteil/isparta`.

**Comment by PinkaminaDianePie** [comment]
@deepsweet you can't install it by ```npm install douglasduteil/isparta``` at all. see folder structure above.

**Comment by deepsweet** [comment]
but you can install it the normal way with `npm install isparta`. I'd like to know why you are trying to install it directly from github repo's master with npm?

btw:
```
Stats
242 downloads in the last day
1,389 downloads in the last week
5,004 downloads in the last month
```

**Comment by PinkaminaDianePie** [comment]
@deepsweet why should i ever try to use default command, if readme has custom command? why do you provide custom command? maybe package name already taken by another lib (good example is nvm) or smth? In readme i see custom command ```npm install douglasduteil/isparta``` so i think there some point for this -_-

**Comment by deepsweet** [comment]
well, I have no idea why README points to `npm install douglasduteil/isparta` because this is not my project. even if package name is already taken there is [scoped packages](https://docs.npmjs.com/misc/scope).

`npm install isparta` works fine as well as `isparta` dependency in `package.json` for me and for 5k downloads in the last month.

anyway, approach with excluding original `src/` from npm package and compiled `lib/` from the git repo is [widely used](https://github.com/search?q=src+.npmignore&type=Code&utf8=%E2%9C%93), and it's just works.

if you *still want* to continue installing package from `douglasduteil/isparta` then make a PR that reverts my changes.

**Comment by joshq00** [comment]
`npm install isparta` does not work for me. the install fails trying to clone `nomnom`

**Comment by loganfuller** [comment]
Is this package still being maintained? Installation is broken.

**Comment by knicholes** [comment]
npm install isparta
npm WARN package.json social@0.0.0 No description
npm WARN package.json social@0.0.0 No repository field.
npm WARN package.json social@0.0.0 No README data
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror git://github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/git-github-com-douglasduteil-nomnom-git-0555a8be
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: Cloning into bare repository '/Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9'...
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: Permission denied (publickey).
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: 
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9: and the repository exists.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "isparta"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/nicholes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/douglasduteil/nomnom.git /Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9
npm ERR! Cloning into bare repository '/Users/nicholes/.npm/_git-remotes/ssh-git-github-com-douglasduteil-nomnom-git-2c2e02e9'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nicholes/code/social/ui/npm-debug.log

**Comment by douglasduteil** [comment]
Might be fixed with the new release https://github.com/douglasduteil/isparta/releases/tag/v3.2.0
Feel free to reopen it if you still have this issue.
