### ISSUE TITLE
Not reporting "Only executed" and "ignored" statements

### ISSUE THREAD

**Issue by albertorestifo** [douglasduteil/isparta#39]
When running Istanbul with the default interpreter, I get an `I` to mark conditional statements that are never passed and an `E` to mark statements that are always executed.

Example:

```js
// to test:
var testMe = function(do) {
  if (do) {
    do = 'ok';
  }
  return do
}

// the if should be marked as I
it('should mark it as ignored', function() {
  testMe();
});

// the if should be marked as E
it('should mark it as ignored', function() {
  testMe(true);
});
``` 

Only if you run both test cases on the function, Istanbul marks the function with green

**Comment by albertorestifo** [comment]
Correction, it's not reporting conditional statements coverage at all:

![image](https://cloud.githubusercontent.com/assets/1037048/7635417/18fdcadc-fa61-11e4-8510-1b0e44d52df4.png)

**Comment by douglasduteil** [comment]
Might be fixed with the new release https://github.com/douglasduteil/isparta/releases/tag/v3.2.0
Feel free to reopen it if you still have this issue.
