### ISSUE TITLE
Statements/Branches/Lines coverage numbers seem wrong

### ISSUE THREAD

**Issue by ezequiel** [douglasduteil/isparta#43]
@douglasduteil 

First off, thanks for the tool. It seems like it's working well.

I am having one issue with it though, which is the coverage numbers are off. For example, it claims this file contains 34 branches, which is incorrect. It only contains one. I'm guessing it's calculating this from the actual compiled Babel output.

Is there anyway around this?

![screen shot 2015-06-24 at 9 14 58 pm](https://cloud.githubusercontent.com/assets/368069/8346756/52ed9464-1ab6-11e5-87ad-1e36e8cd6cef.png)

**Comment by douglasduteil** [comment]
Not yet :)

**Comment by douglasduteil** [comment]
You can try that https://github.com/MalikAbed/istanbul-sourcemap-demo
