### ISSUE TITLE
Trouble using with 6to5ify

### ISSUE THREAD

**Issue by StevenLangbroek** [douglasduteil/isparta#5]
I'm trying to get code coverage reports for an app I'm writing, which is intended to be consumed in an iOS or Android webview. Because of severe bandwidth restrictions, I'm swapping out the `backbone` dependency through a mapping in my `package.json`'s `browser` node. This works in browserify, but apparently isparta doesn't read this. This silently fails and causes my coverage to report 100% coverage, but when I run it from command line I get an error about this dependency. Any idea how I can get proper instrumentation on my Browserified 6to5 code?

**Comment by douglasduteil** [comment]
Use a browserify code coverage tool maybe ?

**Comment by StevenLangbroek** [comment]
I tried that, but if I use a browserify transform for code-coverage, it'll try to apply it to my spec-files as well.

**Comment by lukescott** [comment]
@StevenLangbroek, this is how I did it:
```javascript
var isparta = require("isparta");
var istanbul = require("browserify-istanbul");

module.exports = function(config) {
	config.set({
		frameworks: ["browserify", "mocha", "expect"],
		files: [
			"node_modules/core-js/client/core.js",
			"app/**/*.js",
			"test/**/*.js"
		],
		reporters: ["coverage", "progress"],
		preprocessors: {
			"app/**/*.js": ["browserify"],
			"test/**/*.js": ["browserify"]
		},
		browserify: {
			transform: [istanbul({
				ignore: ["node_modules/**/*.js", "test/**/.js"],
				instrumenter: new isparta.Instrumenter({
					to5Options: {
						optional: ["spec.protoToAssign"]
					}
				})
			})]
		},
		browsers: ["Chrome"]
	});
};
```
I'm using a fork from [this PR](https://github.com/devongovett/browserify-istanbul/pull/8) of browserify-istanbul and istanbul's fork of karma. In this configuration you do not need to use 6to5ify as istanbul already doing the transformation.

**Comment by lastday** [comment]
@StevenLangbroek Thank you very much, this helped me a lot! After few hours of trying to make code coverage work with 6to5 + browserify this finally helped.

**Comment by lukescott** [comment]
Since browserify-istanbul was updated and 6to5 was renamed to babel, here's an updated example:

```javascript
var isparta = require("isparta");
var istanbul = require("browserify-istanbul");

module.exports = function(config) {
    config.set({
        frameworks: ["browserify", "mocha", "expect"],
        files: [
            "node_modules/core-js/client/core.js",
            "app/**/*.js",
            "test/**/*.js"
        ],
        reporters: ["coverage", "progress"],
        preprocessors: {
            "app/**/*.js": ["browserify"],
            "test/**/*.js": ["browserify"]
        },
        browserify: {
            transform: [istanbul({
                instrumenter: isparta,
                instrumenterConfig: {
                    babelOptions: {
                        optional: ["spec.protoToAssign"]
                    }
                }
            })]
        },
        browsers: ["Chrome"]
    });
};
```

**Comment by lastday** [comment]
@lukescott what karma fork should we use? I can't find istanbul fork of karma at the moment.

**Comment by lukescott** [comment]
@lastday [douglasduteil/karma-coverage](https://github.com/douglasduteil/karma-coverage) until [karma-runner/karma-coverage/pull/130](https://github.com/karma-runner/karma-coverage/pull/130) has been merged.

**Comment by lastday** [comment]
@lukescott thank you, that's exactly what I've done.

I just was a bit confused by your phrase 'I'm using a fork from this PR of browserify-istanbul and istanbul's fork of karma'.

**Comment by bendrucker** [comment]
@lukescott's example is excellent. Only thing I'll add as a maintainer of karma-browserify is that it's a hair easier to use the standard browserify transform options syntax: `transforms:[name1, [name2, options]]`

You can do this instead and make things a little cleaner:

```js
transform: [
  ['browserify-istanbul', {
    instrumenter: require('isparta')
  }]
]
```

**Comment by douglasduteil** [comment]
I'm closing this one for now. Feel free to reopen it if you still have this issue.
