### ISSUE TITLE
Command line output

### ISSUE THREAD

**Issue by trevordmiller** [douglasduteil/isparta#50]
Thank you for this! Finally I can use Istanbul/Karma coverage with Babel. One thing: how do you get full command line text-summary output as shown in your demo?

![full-text-summary](https://cloud.githubusercontent.com/assets/5497885/8968893/64ce8d98-35fd-11e5-8ec9-c740db620238.png)

I only get top level stats and have to open the HTML report to drill down, but I'd like to set my karma config to output all stats as you have done.

![top-level-summary](https://cloud.githubusercontent.com/assets/5497885/8968902/6ebd5000-35fd-11e5-9dce-0fc7d49dfb0b.png)

Here is my `karma.conf.js`:

```
var istanbul = require('browserify-istanbul'),
    isparta  = require('isparta');

module.exports =  function (config) {

    config.set({
        basePath: './',

        files: [
    		'./client/src/main.js',
        	'./client/src/components/**/*.js'
        ],

        preprocessors: {
        	'./client/**/*.js': ['browserify', 'babel', 'coverage']
        },

        browserify: {
            debug: true,
            transform: [
                istanbul({
                    instrumenter: isparta
                })
            ]
		},

        coverageReporter: {
            type : 'lcov',
            dir : 'reports/coverage/',
            reporters: [
                { type: 'html', subdir: '.' },
                { type: 'text-summary'}
            ]
        },

        browsers: ['Chrome'],
        frameworks: ['mocha', 'chai', 'browserify'],
        reporters: ['spec', 'coverage'],
        port: 9876,
        colors: true
    });
};
```

**Comment by pewh** [comment]
+1

**Comment by douglasduteil** [comment]
Hi @trevordmiller @pewh 
I'm using the `text` reporter form Istanbul (see https://github.com/karma-runner/karma-coverage/blob/v0.5.3/README.md#advanced-multiple-reporters)
