### ISSUE TITLE
No `includeUntested` Option?

### ISSUE THREAD

**Issue by datatypevoid** [douglasduteil/isparta#51]
I am wondering if there is any `includeUntested` option as there is in `instanbul`? I would think it would be useful to know where completely untested code factors into the equation.

**Comment by douglasduteil** [comment]
Yes

You will find inthe new release https://github.com/douglasduteil/isparta/releases/tag/v3.2.0 the 'include-all-sources' that do. https://github.com/gotwarlost/istanbul/issues/112#issuecomment-98677080)
