### ISSUE TITLE
Publish nomnom fork

### ISSUE THREAD

**Issue by SimenB** [douglasduteil/isparta#52]
Hey,

Could you publish your nomnom-fork to npm? I'd like to use isparta on a box that has no access to the internet, but does have access to npm through a proxy

**Comment by SimenB** [comment]
@douglasduteil Ping :smile:

**Comment by elCarda** [comment]
+1

**Comment by leoselig** [comment]
+1
For us the issue is that we are not using git atm, thus not being able to install git dependencies

**Comment by SimenB** [comment]
@douglasduteil Any news here?

**Comment by douglasduteil** [comment]
Sorry for the wait @SimenB 
https://www.npmjs.com/package/nomnomnomnom is born

**Comment by SimenB** [comment]
Awesome, thanks! I'll give it a whirl at work later today
