### ISSUE TITLE
The license prevents corporate using

### ISSUE THREAD

**Issue by suevalov** [douglasduteil/isparta#53]
Hey, 
first of all thanks for awesome work!

It may sound like a silly request but can you substitute your license by something more friendly for corporate layers? In our project we have to receive juridical approval about using open-source libraries. Likely they won't be happy with this license ;)

Thanks!

**Comment by magmel48** [comment]
+1

**Comment by douglasduteil** [comment]
Sorry I wound change it.
You can still fork and change it is you really need to switch.

**Comment by Storyyeller** [comment]
Why not dual license with a standard liscense?
