### ISSUE TITLE
TAP/tape support

### ISSUE THREAD

**Issue by bucaran** [douglasduteil/isparta#57]
I am using [tap](https://github.com/isaacs/node-tap) for tests and while it does let you tap in coverage enabling a `--coverage` flag, I am not sure how to make it work with `isparta` or ES6.

**Comment by bucaran** [comment]
Nevermind. I figured it out :smile: 

Great job with this module @douglasduteil

**Comment by ArnaudRinquin** [comment]
@bucaran I am trying to use `isparta` with `tap/tape` as well. What was your solution?

**Comment by ArnaudRinquin** [comment]
Ok I figured it out as well: 

`"test": "babel-node `npm bin`/isparta cover --report lcov --report html --report text ./test/index.js | colortape"`

`| colortape` is completely optional here.

**Comment by bucaran** [comment]
@ArnaudRinquin You got it. Also check out https://github.com/bucaran/generator-rise :fist:

**Comment by ArnaudRinquin** [comment]
Oh nice this is exactly the kind of setup I manually build... every damn time.

**Comment by bucaran** [comment]
For sure.
