### ISSUE TITLE
Push karma-coverage changes upstream?

### ISSUE THREAD

**Issue by johlrich** [douglasduteil/isparta#6]
Have you talked with the karma-coverage team about pushing your changes upstream that allow you to support arbitrary instrumentation and have more control over the the passed options? 

I npm installed isparta + 6to5 + your karma-coverage fork to quickly get coverage working on a project with es6 modules that wasn't working with any of the esprima-harmony/esprima-fs based workarounds I tried.

At the very least having isparta becoming a valid option against the main karma-coverage repo would be nice.

**Comment by douglasduteil** [comment]
Hey there @johlrich :) 
Yes I though about it 
But I didn't take the time to actually go through the Karma tests to prove that it's working  :P

**Comment by douglasduteil** [comment]
Alright I made [a PR on the official karma-coverage repo](https://github.com/karma-runner/karma-coverage/pull/130)
We will see if somebody cares or not...
