### ISSUE TITLE
Babel CSS Imports

### ISSUE THREAD

**Issue by markwylde** [douglasduteil/isparta#65]
I've been struggling with this issue all day and I think this project is probably the right place to raise this, but if not my sincere apologies.

I am using `isparta` in my project [react-demo](https://github.com/markwylde/react-demo) and in my `app.js` file I have the following line:

`import '../node_modules/css-reset/reset.css';`

This is fine and compiles great with webpack, since I can specify a bunch of loaders to use, so babel knows how to translate `*.css` files.

Now that I'm using `isparta` as part of `gulp-istanbul` I don't (think I) have a way to tell babel to parse it via the `css-loader`.

I think at this stage it could really just ignore any imports that are not in a config, but maybe there is already a way of solving this, I just haven't managed to find.

My gulp task looks like the following:
```
import { Instrumenter } from 'isparta';

gulp.task('unit_tests', function(cb) {
  gulp.src(['src/**/*.js'])
    .pipe(istanbul({
      instrumenter: Instrumenter,
      includeUntested: true
    }))
    .pipe(istanbul.hookRequire())
    .on('finish', function() {
      gulp.src(['src/**/*.spec.js'])
        .pipe(mocha())
        .pipe(istanbul.writeReports())
        .pipe(istanbul.enforceThresholds({ thresholds: { global: 90 } }))
        .on('end', cb);
    });
});
```

Maybe if there was a way to say:
```
instrumenter: Instrumenter({
    loaders: [{
      test: /\.css$/,
      loader: 'null-loader'
    }]
});
```

Thanks for the help, and also for the outstanding work done on `isparta`. It's been a great experience using the project.

**Comment by douglasduteil** [comment]
I'm closing this for now. Feel free to reopen it if you still have this issue.

**Comment by douglasduteil** [comment]
Did you tried this https://github.com/ColCh/isparta-instrumenter-loader
