### ISSUE TITLE
Coverage on more than one file

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [douglasduteil/isparta#72]
I cannot seem to get isparta to do coverage on more than one file. I am using Tape so when I run the following command `node_modules/.bin/isparta cover test/*.js`, it only reports coverage on the first file in that directory. Any ideas?

**Comment by bucaran** [comment]
Adding myself to the discussion.

**Comment by TYRONEMICHAEL** [comment]
Sorry this is not a limitation with iSparta, but rather with the way node behaves. If you would like to see a solution, you can refer to the following [#11](https://github.com/bucaran/generator-rise/pull/11#issuecomment-147639243). Closing.
