### ISSUE TITLE
Add 6to5 to dependencies

### ISSUE THREAD

**Issue by thejameskyle** [douglasduteil/isparta#8]
You can let npm dedupe the dependency. 

See: https://github.com/SBoudrias/gulp-istanbul/commit/eed2e177f6e73982e78bb97308e3f5dc18d0de08#commitcomment-9575601

**Comment by douglasduteil** [comment]
Alright... The last release were a real mess...
From forces peerDep to weak devDep... to fixed dep...
Still I feel like it's the way to go for me too.

**Comment by douglasduteil** [comment]
BTW @thejameskyle 
My tests tiger some issues on the source maps on 6to5@3.3.9 (https://travis-ci.org/douglasduteil/isparta/builds/49443280)
It's factually failing from  6to5@3.3.4 
\ping @sebmck

**Comment by douglasduteil** [comment]
https://github.com/6to5/6to5/compare/v3.3.3...v3.3.4

**Comment by sebmck** [comment]
@douglasduteil Source maps and istanbul interop was added in 3.3.4, as per the changelog. I'll investigate the source map issues.

**Comment by sebmck** [comment]
It could possibly be that your test data is just incorrect as the source maps were fixed up a bit in 3.3.4.

**Comment by sebmck** [comment]
Can't seem to follow your tests because I'm not familiar with istanbul. Can you verify that the source maps 6to5 is producing is invalid?

**Comment by douglasduteil** [comment]
Yep I'm testing it here https://github.com/douglasduteil/dummy-6to5-karma-coverage

**Comment by sebmck** [comment]
Rolled back commits until it worked, 6to5/6to5@83e225f30ab0d6c41216d1af30c949a9bc0b5851 was the likely one but just needed to confirm.

**Comment by sebmck** [comment]
@douglasduteil Pushed out 3.3.10, should do the job.

**Comment by douglasduteil** [comment]
Wow beautiful :) :+1:

**Comment by douglasduteil** [comment]
Thanks @sebmck

**Comment by douglasduteil** [comment]
I'll improve my test to insure the sourcemap location after 6to5 transformation.
(I'm just testing that es5 code is well located after 6to5 transformation today)
