### ISSUE TITLE
Unable to pass include information to istanbul

### ISSUE THREAD

**Issue by aukevanleeuwen** [douglasduteil/isparta#82]
I was trying to make sure that a certain file was loaded first by isparta / istanbul by passing `--include path/to/first.js --include **/*.js`, however this didn't seem to 'make it to istanbul'. It seems to go wrong on this line:

https://github.com/douglasduteil/isparta/blob/8cd294437e05f38694dea7bc930fda37f41c86df/src/cli.js#L189

Since `ops.includes` is read there where the actual option is called `ops.include` as far as I can tell. I didn't open a pull request since I was unsure whether you wanted to make the cli argument `--includes` (that would be nicely symmetrical with `--excludes`) or that you wanted to fix this on the line mentioned above. I would guess the former, however the commandline argument is a 'public api' of course. Then again: I don't think those includes are working anyway.

**Comment by aukevanleeuwen** [comment]
Probably broke in 941dc51cf13812f22e24ef9eaefd9f7f204ced35.

**Comment by douglasduteil** [comment]
Ooops Right !
I'm correcting this typo right now sry

**Comment by douglasduteil** [comment]
Fixed in isparta@3.5.1

**Comment by aukevanleeuwen** [comment]
:+1: thanks.
